# Home Assistant Add-on Build Configuration
build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm

args:
  REACT_APP_BACKEND_URL: /api

labels:
  org.opencontainers.image.title: "Mise"
  org.opencontainers.image.description: "Self-hosted family recipe management"
  org.opencontainers.image.source: "https://github.com/Domocn/Mise"
  org.opencontainers.image.licenses: "MIT"
